project_name: "intrinsicGSlam_replica"
dataset_name: "replica"
checkpoint_path: null
use_wandb: True
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
mapping:
  # new_submap_every: 50
  # new_submap_every: 5
  new_submap_every: 1000
  map_every: 5
  # map_every: 2
  # iterations: 100 #非新子图第一帧的迭代次数
  iterations: 235
  # iterations: 400

  new_submap_iterations: 1000 #新子图第一帧的迭代次数
  # new_submap_iterations: 100
  new_submap_points_num: 600000  #新子图第一帧均匀采样点云数量
  new_submap_gradient_points_num: 50000 #新子图第一帧梯度采样点云数量
  new_frame_sample_size: -1  #非新子图第一帧的新帧边缘采样点数量
  new_points_radius: 0.0000001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  # pruning_thre: 0.1
  pruning_thre: 0.05
  # pruning_thre: 0.005
  # submap_using_motion_heuristic: True #启发式新增子图
  submap_using_motion_heuristic: False
  lambda_intrinsic: 1.0
  lambda_dssim: 0.2
  # lambda_depth: 0.0
  # lambda_scale_depth: 0.0
  # lambda_reflectance_sparsity: 0.2
  lambda_reflectance_sparsity: 0.2
  lambda_shading_smooth: 0.2
  lambda_prior_chromaticity: 1.0
  lambda_residual: 1.0
  lambda_offset: 1.0
  lambda_residual: 10.0
  lambda_offset: 10.0
tracking:
  gt_camera: False
  w_color_loss: 0.95
  iterations: 60
  # iterations: 41

  cam_rot_lr: 0.0002
  # cam_rot_lr: 0.00002
  cam_trans_lr: 0.002
  # cam_trans_lr: 0.0002

  # odometry_type: "odometer"  # gt, const_speed, odometer
  odometry_type: "gt"
  # odometry_type: "const_speed"
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "point_to_plane" # hybrid or point_to_plane 
  filter_alpha: False
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: False
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  depth_scale: 6553.5


